create table if not exists public.phone_license_transfer_attempts (
  id bigint generated by default as identity primary key,
  requester_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists phone_license_transfer_attempts_requester_idx
  on public.phone_license_transfer_attempts(requester_hash, created_at desc);

alter table public.phone_license_transfer_attempts enable row level security;
revoke all on public.phone_license_transfer_attempts from public, anon, authenticated;

comment on table public.phone_license_transfer_attempts is
  '迁移码失败尝试的短期限流记录，不保存原始IP或设备标识。';
