alter table public.phone_license_transfers
  add column if not exists kind text not null default 'transfer';

alter table public.phone_licenses
  add column if not exists phone_friend_id text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'phone_license_transfers_kind_check'
      and conrelid = 'public.phone_license_transfers'::regclass
  ) then
    alter table public.phone_license_transfers
      add constraint phone_license_transfers_kind_check
      check (kind in ('transfer', 'recovery'));
  end if;
end
$$;

create index if not exists phone_license_transfers_kind_expiry_idx
  on public.phone_license_transfers(license_id, kind, expires_at);

create index if not exists phone_licenses_phone_friend_idx
  on public.phone_licenses(phone_friend_id, created_at desc);

create table if not exists public.phone_license_admin_actions (
  id bigint generated by default as identity primary key,
  license_id uuid not null references public.phone_licenses(id) on delete cascade,
  phone_friend_id text,
  action text not null check (action in ('block', 'recovery')),
  created_at timestamptz not null default now()
);

create index if not exists phone_license_admin_actions_license_idx
  on public.phone_license_admin_actions(license_id, created_at desc);

alter table public.phone_license_admin_actions enable row level security;
revoke all on public.phone_license_admin_actions from public, anon, authenticated;

comment on column public.phone_license_transfers.kind is
  'transfer 为5分钟迁移码；recovery 为一年有效、单次使用的备用恢复码。';
